### ISSUE TITLE
Behave: reorder steps definitions to avoid AmbiguousStep definition

### ISSUE THREAD

**Issue by vincent-psarga** [hiptest/hiptest-publisher#104]
In Behave, the order in which steps are defined is important:

This fails with an AmbiguousStep exception:

        @when(r'I do (.*)')
        def impl(context):
            # This should match "I do things"
            pass

        @when(r'I do (.*) and (.*)')
        def impl(context):
            # This should match "I do things and stuff"
            pass

This is ok:

        @when(r'I do (.*) and (.*)')
        def impl(context):
            # This should match "I do things and stuff"
            pass

        @when(r'I do (.*)')
        def impl(context):
            # This should match "I do things"
            pass

We need to reorder the steps definitions to avoid this issues.

**Comment by cbliard** [comment]
Available in hiptest-publisher 1.12.0
