### ISSUE TITLE
Add the dataset names in scenario outlines for Gherkin languages

### ISSUE THREAD

**Issue by aurelien-reeves** [hiptest/hiptest-publisher#105]
From @tim-littlefair-vix here: https://github.com/hiptest/hiptest-issue-tracker/issues/132

### Steps to reproduce
1. Create a scenario with a datatable of examples in the hiptest web interface.  Put meaningful values in the "dataset name" column summarizing the reason for existence of each line in the examples table (e.g. "Using ticket before expiry time", "Using ticket after expiry time").
2. generate the feature file using hiptest publisher
3. Add the scenario to a test run and confirm that the meaningful names entered for each line is visible

### Expected behaviour
Meaningful names should be exported as part of the feature file gherkin

### Actual behaviour
Column is not visible in exported gherkin.  This is a maintainability issue as it means that maintainers who are tweaking the gherkin (either as an experiment or with a view to round-tripping it back to Hiptest) don't have access to the intent of each row in the table
Also, when tests are run using Java-cucumber the rows from the example table are identified by a string of parameter values which is hard to interpret without the parameter names.  If the dataset name column was in the table, J-c would display it as one of these values which would be helpful.

### My configuration
Chrome

**Operating system:**
Windows 7

**Comment by cbliard** [comment]
Available in hiptest-publisher 1.12.0
