### ISSUE TITLE
Setup actionwords are not added to test in subfolders

### ISSUE THREAD

**Issue by fasolens** [hiptest/hiptest-publisher#111]
Steps from Setup of directory/subdirectory are not added to tests file generated in hiptest platform
 
### Steps to reproduce
1. On Hiptest platform create project
2. Create subfolders in project
ProjectFolder
  -> Subfolder1
    -> Subfolder2
3. In 'Subfolder1' add to Setup (pre-condition) actionword
4. in 'Subfolder2' add to Setup actionword
5. Add test 'FooTest' with steps
6. update test definitions with hiptest-publisher or download test from hiptest platform
7. Actionword from Setup of Subfulder2 are not included in test definition of 'FooTest'

I have use protractor publisher but also tested in Rspec

### Expected behaviour
Actionword from Setup should be added in beforeEach closure before all tests from 'Subfolder2'

### Actual behaviour
Actionword from Setup is omitted during tests generation

### My configuration
**Browser:**
Chrome

**Operating system:**
Linux Mint 19 Tara

**Comment by blethier** [comment]
Hello.

You need to add the `with folders` option when exporting your project.

Using the hiptest-publisher gem :
It can be configured using a command line argument (--with-folders) or you can configure it directly on the protractor.conf file by adding this line `with_folders = true`

From hiptest plateform:
On the automation page click on [Hiptest-publisher as a service](https://hiptest-publisher.scalingo.io/) and select "Create a directory structure" on Structure export.

Regards.
