### ISSUE TITLE
Add support for CodeceptJS

### ISSUE THREAD

**Issue by FatimaEzzahraIdrissi** [hiptest/hiptest-publisher#115]

**Comment by tommyboylab** [comment]
CodeceptJS would allow for the use of multiple backends under the same syntax (including Webdriver and Puppeteer)... I think it'd be immensely beneficial. https://codecept.io/helpers/

**Comment by HoudaDabou** [comment]
Hi @tommyboylab,

Our team has added this integration request of CodeceptJS, you can find the related Trello card [here](https://trello.com/c/4udxbFo3).

Please upvote for them to increase their priority in our production.

Thanks in advance for your vote!

Regards,

**Comment by HoudaDabou** [comment]
Hi all!

Good news, the integration for CodeceptJS is now available :)

Here is the related [hps repository](https://github.com/hiptest/hps-javascript-codeceptjs) that gives you an example with this integration based on the "Coffee Machine" HipTest sample project.

**Comment by mfathallah** [comment]
I noticed a problem in the execution of tests with codeceptjs even in the project of coffee machine. the background / setup does not work.
in the coffee machine project, you can start seperating the water suite and you will find that it does not work.
  ✖ "after each" hook: codeceptjs.after for "Message "Fill water tank" is displayed after 50 coffees are taken (<hiptest-uid>) @priority-0" in 44ms

**Comment by HoudaDabou** [comment]
hmm after trying to execute the tests for this [hps-javascript-codeceptjs](https://github.com/hiptest/hps-javascript-codeceptjs ) based on the "Coffee Machine" sample project, I noticed the same issue as you :(

Certainly my colleague @vincent-psarga can give more helpful instructions to solve that!
