### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by doncorsean** [hiptest/hiptest-publisher#117]
When I use hiptest-publisher the Actionwords file does not have an import for DataTable and compilation fails. The Step definitions file has the imports but Action words does not.

```
[ERROR] src/test/java/automation/ncl/stepdefs/Actionwords.java:[109,46] cannot find symbol
[ERROR]   symbol:   class DataTable
[ERROR]   location: class automation.ncl.stepdefs.Actionwords
[ERROR] src/test/java/automation/ncl/stepdefs/Actionwords.java:[481,40] cannot find symbol
[ERROR]   symbol:   class DataTable
[ERROR]   location: class automation.ncl.stepdefs.Actionwords

```

**Comment by vincentcapicotto** [comment]
Hello ;),

The Actionwords file is a file containing an empty definition of action words. The developer must implement the different definitions. If one (or more) of these definitions uses a datatable parameter, it must manually import the Datatable class.

I hope it helps
Vincent

**Comment by doncorsean** [comment]
Thank you Vincent, understood. One other issue we're having is attaching jenkins jobs to the test runs. The job lookup feature never returns with a list of Jenkins jobs to select. I've let it sit for 30-40 minutes with no success. The Jenkins credentials validate for that project but I'm unable to link to Jenkins.

**Comment by vincentcapicotto** [comment]
You are welcome.
For your issue, to begin could you try to visit this page: https://app.hiptest.com/browser-health-check, and tell me if all items in the connectivity panel are checked.

**Comment by doncorsean** [comment]
Yes, all items report ✅

**Comment by HoudaDabou** [comment]
Hi,

Is this question still relevant?

Regards,
Houda
