### ISSUE TITLE
Push Attachments to Hiptest

### ISSUE THREAD

**Issue by tommyboylab** [hiptest/hiptest-publisher#122]
I've been using Cypress in Hiptest for the past few months and so far it has been great. 

I had a question regarding the capability of Hiptest-Publisher to push more than the test reports back to Hiptest: notably the screenshots that Cypress can capture upon a failing test. 

I know that tests (under the test run) are capable of having attachments and I was wondering if there was a way to push these screenshots back to Hiptest as such.

I think that would be an extremely helpful feature to have, regardless of the testing framework as a CI could output and push logs, videos or screenshots appended to the test that ran which would help better pinpoint points of failure and other data not available to be pushed with the current report formats.

![screen shot 2019-02-13 at 2 26 38 pm](https://user-images.githubusercontent.com/44362297/52715214-21347380-2f9c-11e9-8dec-1d2d78c19d37.png)

**Comment by HoudaDabou** [comment]
Hi @tommyboylab,

Our team has added this feature request in our backlog, you can find the related Trello card [here](Attach files with test execution reports when pushing results with hiptest-publisher).

Please upvote for it to increase its priority in our production.

Thanks in advance for your vote!

Regards,
Houda

**Comment by HoudaDabou** [comment]
Hi agin @tommyboylab,

Feel free to follow the progress of its development from our backlog.

So, I close this issue.

Regards,
Houad
