### ISSUE TITLE
Feature empty

### ISSUE THREAD

**Issue by TimotheeVille** [hiptest/hiptest-publisher#123]
```gherkin
Given we have a folder "Feature 1" with scenarios in an empty folder of the same name
When we export the feature file
Then we have an empty feature file
```

Hierarchy:
Root
    |---- Feature 1 (id: 10)
                 |---- Feature 1 (id: 20)
                              |----- Scenario 1
                              |----- Scenario 2

Config file
```bash
# hiptest-publisher.conf
token=<token>
language=cucumber
filter_on_folder_ids=20
feature_name="Feature 1"
no_uids=1
no_parent_folder_tags=1
```

The exported feature file is empty

**Comment by HoudaDabou** [comment]
This issue has been fixed by our team.
