### ISSUE TITLE
Datatable shortkey like Microsoft Excel

### ISSUE THREAD

**Issue by araqieldev** [hiptest/hiptest-publisher#126]
Hi,

I think missing feature in datatable completion.
When we will fill many data in datatable, we would like to use the insertion method like Microsoft Excel.
`Tab` key to go to the next column.
`Enter `key to go to the next row (create if you are the end of the table).

What do you think ?
Thanks

**Comment by HoudaDabou** [comment]
Hi @araqieldev,

You can copy/paste the data from your Excel to the "Raw version" mode of the datatable's scenario.
Just save your spreadsheet to .csv format, and with a pipeline | as separator.

Here is a [short recording](https://smartbear.box.com/s/mvucpnk97yqp61l79vjxucjlz1xn7ftk) that illustrates the above explanations.

Does that meet your need?

Regards,
Houda
