### ISSUE TITLE
New v1.22.0 release

### ISSUE THREAD

**Issue by Jesterovskiy** [hiptest/hiptest-publisher#128]
Hi. Are we ready for new release or waiting for some feature/bugfix? Thanks)

**Comment by Jesterovskiy** [comment]
@cbliard maybe you can help again?)

**Comment by HoudaDabou** [comment]
Hi @Jesterovskiy,

Can you give me more details about feature/bug fixing  that you need please?

**Comment by Jesterovskiy** [comment]
@HoudaDabou Hi. I Just want new release with fixes, that already in master. That's all =)

**Comment by HoudaDabou** [comment]
Sorry I didn't check your commits :)

So we'll keep you informed about the release ASAP.

Thanks for your patience.

**Comment by Jesterovskiy** [comment]
Thank you)

**Comment by vincent-psarga** [comment]
There will be a release during the day (1.22.0)

Sorry for the delay, there was some things waiting on our side to be integrated to HP which were finally delayed.
