### ISSUE TITLE
The project secret token must be numeric - ENV Variable

### ISSUE THREAD

**Issue by tommyboylab** [hiptest/hiptest-publisher#133]
I'm trying to place both my Secret Token and Test Run ID into a .env file. I'm getting the above error when using the variables in both a .config file as well as in package.json. 

How would I use an env variable with hiptest-publisher?

**Comment by HoudaDabou** [comment]
Hi @tommyboylab,

You can define env variables but into your CI tool for example, or in a file in your application to have this:

`hiptest-publisher -c hiptest-publisher.conf --token=${SECRET_TOKEN} --test-run-id=${TEST_RUN} --only=features `


But you cannot store these env variables in the hiptest-publisher configuration file itself, you must remove the 'token' parameter and the 'test_run_id' parameter from this config file.

Maybe this explanation is not enough clear? If so, can you send us your hiptest-publisher config file and the necessary information (how would you like to perform this task and how do you proceed currently) please by email to: support@hiptest.com

Thanks in advance!

**Comment by HoudaDabou** [comment]
HI @tommyboylab,

Do you still experience this issue?
