### ISSUE TITLE
Add Spock support

### ISSUE THREAD

**Issue by vincent-psarga** [hiptest/hiptest-publisher#15]
http://spockframework.github.io/spock/docs/1.0/index.html

**Comment by SchlammSpringer** [comment]
As I already mentioned in the [commit](https://github.com/hiptest/hiptest-publisher/commit/2cab93435a173b7ea65780553869f1f09f0e4da4) thank you for the integration. Please retry if the `where` Table is working when you add the `spock.lang.Unroll` above the method. 
Thank you.

**Comment by vincent-psarga** [comment]
This fix should be released Monday :)

**Comment by SchlammSpringer** [comment]
Thank your for the support, @lostiniceland and I will try to keep on supporting you.
