### ISSUE TITLE
Gem install in Ruby 2.6.5

### ISSUE THREAD

**Issue by rodolfoholy** [hiptest/hiptest-publisher#167]
**Describe the bug**
Trying to install gem hiptest-publisher on Ruby 2.6.5

**To Reproduce**
gem install hiptest-publisher

**Expected behavior**
I expect to install the gem successfully.

**What I got?**
$ gem install hiptest-publisher
ERROR:  Error installing hiptest-publisher:
        The last version of nokogiri (~> 1.8, < 1.10) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1` and then running the current command again     
        nokogiri requires Ruby version >= 2.2, < 2.6. The current ruby version is 2.6.5.114.

And, when I try to install nokogiri -v 1.9.1
ERROR:  Error installing nokogiri:
        The last version of nokogiri (= 1.9.1) to support your Ruby & RubyGems was 1.9.1. Try installing it with `gem install nokogiri -v 1.9.1`
        nokogiri requires Ruby version >= 2.2, < 2.6. The current ruby version is 2.6.5.114.

**Context & Motivation**
I'm trying to integrate our automation with Hiptest

**Your Environment**
Windows 10

ruby 2.6.5p114 (2019-10-01 revision 67812) [x64-mingw32]

nokogiri (1.10.5)
    Platform: x64-mingw32
    Authors: Aaron Patterson, Mike Dalessio, Yoko Harada, Tim Elliott,
    Akinori MUSHA, John Shahid, Lars Kanis
    License: MIT
    Installed at: C:/Ruby26-x64/lib/ruby/gems/2.6.0

**Additional context**
Sorry, I tried everything to solve this but I don't find any info on web neither stackoverflow.

**Comment by vincent-psarga** [comment]
Hi,

The reason why we postponed (maybe too much ..) the Nokogiri upgrade is that it will induce a breaking change of `hiptest-publisher` (removing the support of `ruby-2.2`).
I'm pretty surprised it does not work with `2.6.5` (our CI uses `2.6.2` and can install `nokogiri`, which seems contradictory with the message you are facing).

I'll try to find time before the end of the week to release version `2.0` of `hiptest-publisher` that will support a more recent Nokogiri.

**Comment by rodolfoholy** [comment]
Thanks for ur answer and support Vincent!

**Comment by vincent-psarga** [comment]
I just release `hiptest-publisher` version `2.0.0` which uses Nokogiri `1.10`. This should fix your issue.

Could you tell if this fixes your problem ?

**Comment by rodolfoholy** [comment]
```
$ gem install hiptest-publisher
Fetching hiptest-publisher-2.0.0.gem
Successfully installed ruby_version-1.0.1
Successfully installed parslet-1.8.2
Successfully installed ruby-handlebars-0.4.0
Successfully installed hiptest-publisher-2.0.0
Parsing documentation for ruby_version-1.0.1
Installing ri documentation for ruby_version-1.0.1
Parsing documentation for parslet-1.8.2
Installing ri documentation for parslet-1.8.2
Parsing documentation for ruby-handlebars-0.4.0
Installing ri documentation for ruby-handlebars-0.4.0
Parsing documentation for hiptest-publisher-2.0.0
Installing ri documentation for hiptest-publisher-2.0.0
Done installing documentation for ruby_version, parslet, ruby-handlebars, hiptest-publisher after 6 seconds
4 gems installed
```

Done! Thanks a lot!

**Comment by vincent-psarga** [comment]
You're welcome :)
