### ISSUE TITLE
Disable color

### ISSUE THREAD

**Issue by ylacaute** [hiptest/hiptest-publisher#171]
When executing HipTest inside a Jenkins pipeline, special color characters are displayed, giving something like **"[[0;31;49mx[0m]"**.

Most of the time, enterprises will not install plugins like "ansicolor-plugin", so it could be a good idea to add a no color option, it could be something like "--no-color" or "--batch".

**Comment by vincent-psarga** [comment]
I've added a PR with code that should add the `--no-color` option. This should be merged & released after the holidays :)

**Comment by cbliard** [comment]
Once PR is merged, adding `--no-color` will probably not even be necessary as we now activate colored output only if it is a tty.
