### ISSUE TITLE
Push ignores test run ID parameter

### ISSUE THREAD

**Issue by mhfrantz** [hiptest/hiptest-publisher#31]
It seems that regardless of the `test_run_id` specified in the config file, Hiptest Publisher will push all of the test results.  For example, if the JUnit XML test results contain scenarios with UID's from multiple test runs, but I try to push only one of them with the `--test-run-id=X` option, it will push all of the results.

Is the test run ID necessary?  Will the server simply look for the UID's anyway no matter which test run ID I specify?

**Comment by cbliard** [comment]
The test run id is not necessary. As you guessed the server will always look for the UIDs in the sent test result file.

**Comment by mhfrantz** [comment]
OK, I can understand this design, and agree that it can be considered "working as intended."

Also, for the "external tests" integration described [here](https://docs.hiptest.net/create-a-test-run-for-your-unit-tests/), it looks like Hiptest Publisher is not involved in that push.  If it were, then the test run ID parameter might be required.
