### ISSUE TITLE
escape_new_line fails with nil input

### ISSUE THREAD

**Issue by mhfrantz** [hiptest/hiptest-publisher#32]
This can happen if a template uses `escape_new_line` in an actionword argument template (e.g. `argument.hbs` in many language packs), and the scenario is in a broken state where an AW parameter has not been defined.

I have a fix.

**Comment by vincent-psarga** [comment]
Thanks again for the contribution (we'll have to send you chocolates again :D ). The fix has been released in 0.15.3.
