### ISSUE TITLE
cannot set --no-uids to true

### ISSUE THREAD

**Issue by aznime** [hiptest/hiptest-publisher#40]
Using hiptest-publisher 0.16.2, I cannot set --no-uids to true from the command line nor from a config file

**Comment by cbliard** [comment]
Thank you for reporting this bug. It has been fixed in hiptest-publisher 0.17.0

Run `gem install hiptest-publisher` to upgrade.

**Comment by SupportHT** [comment]
Merci ChristoP
Laurent PY

Product Manager

Mobile +33 6 88 77 65 91 Twitter @py_laurent Skype laurent.py

Hiptest.net <http://hiptest.net/>  Every test should tell a story to deliver software that matters
