### ISSUE TITLE
Improvement : Easy solution for supporting cucumber.json

### ISSUE THREAD

**Issue by settlersxp** [hiptest/hiptest-publisher#42]
After the least webinar there was another team asking about support for cucumber.json.

I have found this git repo: https://github.com/stjohnjohnson/cucumber-junit

I think it can be included as it is in hiptest and later if you guys feel like it re-write.

**Comment by vincent-psarga** [comment]
In fact the JUnit XML generated by this tool is not compatible with what we expect in Hiptest (each feature is represented as a test suite, each step as a test case).
I made a fork of this project generating a test for each test instead, it can be found here: https://github.com/vincent-psarga/cucumber-junit

You can see in this repository how it integrates: https://github.com/hiptest/hps-cucumber-javascript

In the package.json file, this line is needed: "cucumberjs-junit": "git://github.com/vincent-psarga/cucumber-junit.git"

And generating the XML file after running the tests: node_modules/.bin/cucumber-js --format=json | node_modules/cucumber-junit/bin/cucumber-junit --features-as-suites > junit_output.xml
