### ISSUE TITLE
cucumber java templating fail

### ISSUE THREAD

**Issue by atulhm** [hiptest/hiptest-publisher#43]
I'm trying to override the generated ActionWords.java.  This works fine by creating and specifying an override-template folder and creating actionwords.hbs

The problem is that the same actionwords.hbs is used to generate StepDefinitions.java

proposed solution: maintain lib/templates directory structure so that one could create files such as:
override-templates/cucumber/java/actionwords.hbs
override-templates/java/actionwords.hbs

OR

do not use conflicting filenames that would only allow a single template file to be overriden.

**Comment by vincent-psarga** [comment]
That makes sense. The overriden-templates works fine for "classical" languages/framework, but we did not think we'd have this kind of issues with Gherkin based languages.
We'll add that to our backlog :)

**Comment by atulhm** [comment]
Already fixed.  Probably should have wrapped the map loop in an if but I'm not a ruby expert.   I submitted a pull request.

I believe I've found a relatively clean way to develop and maintain cucumber java tests while test scenarios are in active development.

We're going to try the process out internally this week.

**Comment by vincent-psarga** [comment]
Thanks for the pull request :) I merged it but the public release will certainly wait next week, most of the team is at the EuroStar conference this week.
