### ISSUE TITLE
Cannot export attachments

### ISSUE THREAD

**Issue by gpapadakis** [hiptest/hiptest-publisher#51]
There is a feature in scenarios to be able to upload attachments (providing data in files like .xslt). We need to be able to export those files along with .feature files using hiptest-publisher cli tool.

Thanks

**Comment by HoudaDabou** [comment]
Hi @gpapadakis,

This feature request has been added to our backlog, thanks to upvote for the related Trello card [here](https://trello.com/c/LiOeyw8A) to increase its priority in our production.

Thanks in advance for your vote!
