### ISSUE TITLE
Export folder without subfolders

### ISSUE THREAD

**Issue by tikolakin** [hiptest/hiptest-publisher#59]
Hello
is there a way to export features without subfolders, using hiptest publisher?
currently
when I do the following
`./hiptest --token="token" --only=tests --filter-on-folder-ids=254812`
it will pull scenarios from the folder with id 254812 and all child folders
but I might want to pull only scenarios from the 254812, without any child directories
is there a way to make to make it happen?

**Comment by vincent-psarga** [comment]
Hi Tiko,

That's not possible yet but I'll see if we can add easily a "--no-subfolders" option when filtering on folders.

Best regards,
Vincent

**Comment by tikolakin** [comment]
Thanks, @vincent-psarga I will appreciate this functionality in any upcoming release.  As it's kinda a big issue with our test management of automated/manual scenarios

**Comment by vincent-psarga** [comment]
In 1.4.0, there is now the --not-recursive option that can be used in conjunction with --folder-on-tag-name and --filter-on-tag-id :)

**Comment by tikolakin** [comment]
appreciate @vincent-psarga
