### ISSUE TITLE
Nightwatch.js support

### ISSUE THREAD

**Issue by hiptest** [hiptest/hiptest-publisher#6]

**Comment by angell-ec** [comment]
After discussing with our team, a practical approach might be: 
* Each action word is exported to either a custom assertion or command
* Each test can then be exported as nightwatchjs tests, which will use the custom assertions and commands listed above
* Assertion and commands can be either in tests/ or pageobjects/ but for organizational sake it might make more sense to put in tests
** (it might also be possible to write custom functions and assign them action words - which uses default commands and assertions - then exports hiptest tests as nightwatchjs tests that uses the custom functions)

As far as testing it, we can try to use it and run it and report any issues we might have with it.

**Comment by hiptest** [comment]
Thanks for the feedback :)

**Comment by darita92** [comment]
Any update on support for nightwatch?

**Comment by lee-alderdice** [comment]
For those using vue-cli this would be a huge help ... any release map for this?

**Comment by HoudaDabou** [comment]
Hi there,

Our team has added this integration request of Nightwatch.js, you can find the related Trello card [here](https://trello.com/c/YKzZVI2D).

Please upvote for them to increase their priority in our production.

Thanks in advance for your vote!

Regards,
Houda

**Comment by cbliard** [comment]
We do not plan to add nightwatch for now. I'm closing this one.
