### ISSUE TITLE
Javascript Setup not included

### ISSUE THREAD

**Issue by tschechniker** [hiptest/hiptest-publisher#63]
Hi,

i'm using protractor to test our apps but the Setup section which i can define in HipTest is not getting rendered in the code. If i test it with Behat it's working only for Javascript it's not working. 

Best regards

Tschechniker

**Comment by vincent-psarga** [comment]
Hi,

You need to use the option --with-folders (or with_folders=true in the config file) to get the setups rendered.

You can see here an example of code generated with the setup: https://github.com/hiptest/hps-protractor/blob/master/e2e-tests/display_errors/beans_test.js

Best regards,
Vincent
