### ISSUE TITLE
When downloading by filter status, utility is not downloading in only=features format

### ISSUE THREAD

**Issue by binoyshah90** [hiptest/hiptest-publisher#66]
When we are running following command it's downloading in feature file format:

hiptest-publisher --token {token} --test-run-id {test-run-id} --config-file hiptest-publisher-cukes.conf

But when we run following command it's not downloading in feature file format

hiptest-publisher --toke{token} --test-run-id {test-run-id} --config-file hiptest-publisher-cukes.conf --filter-on-status=failed

Contents of hiptest-publisher-cukes.conf file: 
language = cucumber
output_directory = './hiptest-features'
framework = javascript
with_folders = true
split_scenarios = false
leafless_export = false
no_uids = false
keep_filenames = false
keep_foldernames = false
only = features

**Comment by binoyshah90** [comment]
Anyone working on this?

**Comment by binoyshah90** [comment]
This is a case of i want to download only such features which are failed in last build. That will help me to re-run the failed one.

**Comment by TimotheeVille** [comment]
Let me investigating on this!

**Comment by TimotheeVille** [comment]
Can you please try to remove `only = features` from your config file and add `without = actionwords` to it?

**Comment by binoyshah90** [comment]
I tried as you suggested "remove only = features from your config file and add without = actionwords" but it only downloaded step-definitions

**Comment by binoyshah90** [comment]
let me tell you the difference here: 
1. When we are executing first command without filter status it's downloading an xml file and converting it to feature file if i am not wrong.
2. When you are executing second command with filter status it's not downloading an xml file and i think it's failing there when converting from xml to feature file.

**Comment by binoyshah90** [comment]
Why you closed this one. It's still not working.

**Comment by binoyshah90** [comment]
Why you closed this one. It's still not working.

**Comment by TimotheeVille** [comment]
Sorry, a commit automatically close this issue. It's going be solved, but we have to wait for the Hiptest CI/CD to do its job.

**Comment by binoyshah90** [comment]
Gotcha. Thanks a ton for your help. I'll wait for the patch.

**Comment by TimotheeVille** [comment]
Patch has been deployed, please let me know if it solve your issue!

**Comment by binoyshah90** [comment]
Where i can get the patch version. Kindly send me a link.

**Comment by cbliard** [comment]
You do not have to download a new version of hiptest-publisher as the issue was on the server side. The data sent from the server was missing some information when using filters.

It should work as expected now.

**Comment by binoyshah90** [comment]
Perfect. Working as expected now.

**Comment by cbliard** [comment]
Great! Thank you for reporting this issue.
