### ISSUE TITLE
Categorised tags aren't exported to feature files correctly

### ISSUE THREAD

**Issue by inqa** [hiptest/hiptest-publisher#71]
Categorised tags are changed to normal tags when exporting to feature files, as the delimiter character between category and tag is converted from :  to -

**Steps to re-produce:**
* In a test scenario, add a categorised tag, eg: 
![image](https://user-images.githubusercontent.com/26392478/33190454-d870dd66-d0a4-11e7-8977-c14d5fc9766e.png)
(where the semi colon is the delimiter between category and tag.
* Export to feature file with hiptest-publisher
* Observe in the feature file that @sprint-1 appears as a tag for the scenario 

**Expected result:**
@sprint:1 should appear in the feature file so categorisation is maintained.

**Comment by vincent-psarga** [comment]
Hi,

This was done on purpose as the semi-colon notation has a different meaning in Cucumber than in Hiptest (https://github.com/cucumber/cucumber/wiki/Tags#tag-limits-and-wip).

It is possible to override the way hiptest-publisher exports tags to keep the semi-colon but you may loose the ability to set limits during test execution.

Best regards,
Vincent
