### ISSUE TITLE
Gherkin: escape pipes in datatables and step datatables

### ISSUE THREAD

**Issue by aurelien-reeves** [hiptest/hiptest-publisher#90]
In hiptest datatable we may have pipes.
They should be escaped when exported in a Gherkin Example.

Also step datatables may have escaped pipes. Hiptest-publisher escape the escape character resulting in the escape character being escaped, but the pipe not being escaped anymore.

**Comment by TimotheeVille** [comment]
Fixed in hiptest-publisher 1.10.7
