### ISSUE TITLE
Error Installing

### ISSUE THREAD

**Issue by yael-lorenzo-olx** [hiptest/hiptest-publisher#95]
ubuntu 16.4

sudo apt-get install ruby-full

sudo gem install hiptest-publisher

`Building native extensions.  This could take a while...
ERROR:  Error installing hiptest-publisher:
	ERROR: Failed to build gem native extension.

    current directory: /var/lib/gems/2.3.0/gems/nokogiri-1.8.2/ext/nokogiri
/usr/bin/ruby2.3 -r ./siteconf20180322-29584-1cvzcd.rb extconf.rb
checking if the C compiler accepts ... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/usr/bin/$(RUBY_BASE_NAME)2.3
	--help
	--clean
/usr/lib/ruby/2.3.0/mkmf.rb:456:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /usr/lib/ruby/2.3.0/mkmf.rb:571:in `block in try_compile'
	from /usr/lib/ruby/2.3.0/mkmf.rb:522:in `with_werror'
	from /usr/lib/ruby/2.3.0/mkmf.rb:571:in `try_compile'
	from extconf.rb:138:in `nokogiri_try_compile'
	from extconf.rb:162:in `block in add_cflags'
	from /usr/lib/ruby/2.3.0/mkmf.rb:629:in `with_cflags'
	from extconf.rb:161:in `add_cflags'
	from extconf.rb:410:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.2/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /var/lib/gems/2.3.0/gems/nokogiri-1.8.2 for inspection.
Results logged to /var/lib/gems/2.3.0/extensions/x86_64-linux/2.3.0/nokogiri-1.8.2/gem_make.out`

**Comment by yael-lorenzo-olx** [comment]
It was not a permission issue. I have used sudo.

This made the trick. 

apt install build-essential

At the end Linux is getting like Microsoft, getting "essential" things to work.

**Comment by cbliard** [comment]
You are right, I overlooked the installation log. Glad you figured it out.
